version: '3'
    
services:
  py:
    image: jupyter/datascience-notebook
    stdin_open: true
    tty: true

    ports:
      - "8888:8888"
      - "8889:8889"
      - "4040:4040"

    user: root
    
    command: bash -c "cd /code &&
                      apt-get update && apt-get upgrade -y &&
                      pip install --upgrade pip setuptools wheel &&
                      pip install -r pip-requirements.txt &&
                      jupyter lab --allow-root --notebook-dir /code/main &&
                      touch anything && tail -f anything"

    volumes:
      - .:/code